### ISSUE TITLE
No support for Node 0.10 & 0.12?

### ISSUE THREAD

**Issue by jd327** [jamonkko/babel-plugin-rename-umd-globals#5]
Or am I missing something...

```
TypeError: test.js: Object post has no method 'includes'
    at Object.exit (/tmp/test.js/node_modules/babel-plugin-rename-umd-globals/node_modules/babel-plugin-rename-assigned-properties/lib/index.js:113:44)
```

**Comment by jamonkko** [comment]
Little bit late to the party, but yes it seems that I need to polyfill _includes_ to make it work with ES5. (http://stackoverflow.com/q/31427293)

But I think I'm just going to use indexOf instead.
